import type { Metadata } from 'next';
import {  Manrope } from 'next/font/google';
import '@/styles/main.scss';
import '@/styles/_editor.scss';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={manrope.className}>{children}</body>
		</html>
	);
}
